kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sticky-reader-role
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
kind: ServiceAccount 
apiVersion: v1
metadata:
  namespace: ${config.namespace}
  name: pod-reader-account

--- 
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-cluster-role-binding
  namespace: ${config.namespace}
subjects:
- kind: ServiceAccount
  name: pod-reader-account
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: sticky-reader-role
  apiGroup: rbac.authorization.k8s.io
