kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: sticky-reader-role
rules:
- apiGroups: [""] 
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
kind: ServiceAccount 
apiVersion: v1
metadata:
  namespace: default
  name: pod-reader-account

--- 
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: pod-reader-account
  apiGroup: ""
roleRef:
  kind: Role
  name: sticky-reader-role
  apiGroup: rbac.authorization.k8s.io
